# _config.yml

url: "" # the base hostname & protocol for your site, e.g. http://example.com
baseurl: "" # the subpath of your site, e.g. /blog
title: "Jekyll + Tailwind" # the name of your site, e.g. ACME Corp.

# Build settings
plugins:
  - jekyll-feed
  - jekyll-postcss

plugins:
  - jekyll-postcss

postcss:
  cache: false
